### ISSUE TITLE
save the loaded document and annotations on local and reload it

### ISSUE THREAD

**Issue by hesampour** [syncfusion/ej-angular2#10]
Is there a way to save the loaded document in local and reload it again? or Is there a way to just load pdf locally and not connecting to the server?
thanks

**Comment by karthik-chan** [comment]
Hi @hesampour 
No, we do not have support for loading existing PDF document through a client-side library. To achieve your requirement you have to make use of our server-side Essential PDF library.
Regards,
Karthikeyan
